// Auto-generated header for mandel
// Generated by lua2cpp

#pragma once

#include "../runtime/globals.hpp"

TABLE complex(x_t x, y_t y);
template<typename T1, typename T2> auto Complex_conj(T1 x, T2 y);
template<typename T1> auto Complex_norm2(T1 x);
template<typename T1> auto Complex_abs(T1 x);
template<typename T1, typename T2> auto Complex_add(T1 x, T2 y);
template<typename T1, typename T2> auto Complex_mul(T1 x, T2 y);
double abs(x_t x);
template<typename T1, typename T2> auto level(T1 x, T2 y);
void mandel_module_init(TABLE arg);
